output_root: ./runs
name: mnist_ebm

dataset:
  cls: torchvision.datasets.MNIST
  params:
    root: ./data
    train: True
    download: True

ood_dataset:
  cls: torchvision.datasets.FashionMNIST
  params:
    root: ./data
    train: True
    download: True

ebm:
  cls: implicit.models.ebm.EBM
  params:
    lims: [0.0, 1.0]
    buffer_size: 10000

  energy:
    cls: implicit.maps.smooth.ImageSmoothMap
    params:
      dom_shape: [1, 28, 28]
      codom_dim: 1
      hidden_channels: 256
      num_layers: 4
      pool_size: null
      spectral_norm: True

  training:
    # General parameters
    optimizer:
      cls: torch.optim.Adam
      params:
        lr: 0.0003
    batch_size: 128
    epochs: 200

    # Callbacks for logging
    callbacks:
      - cls: callbacks.UpdateProgressBarStats
        params:
          freq: 1
      - cls: callbacks.SaveStatsToTensorBoard
        params:
          freq: 1
      - cls: callbacks.SampleToTensorBoard
        params:
          freq: 50
          sample_kwargs:
            size: 64
      - cls: callbacks.SaveModel
        params:
          freq_epochs: 5
      - cls: callbacks.EvaluateFID
        params:
          batch_size: 256
          freq_epochs: 5
          sample_kwargs:
            mc_kwargs:
              n_steps: 0
      - cls: callbacks.EnergyOODHistogram
        params:
          freq_epochs: 1

    beta: 0.1
    buffer_frac: 0.95
    mc_kwargs:
      alpha: 10
      eps: 0.005
      n_steps: 20
      grad_clamp: 0.03
